### ISSUE TITLE
Contradicting Description

### ISSUE THREAD

**Issue by saiteja09** [SoftwareEngineeringToolDemos/FSE-2011-Querypoint#3]
In the Readme File I could see that you have linked it to Official Google Code Project Repository where I can find the Source Code and you have uploaded the same in this repository too. But you have specified that there is no Source Code available in ReadMe file. This looks contradicting and confusing.

**Comment by sktomer** [comment]
the project files imported are mainly files related to the querypoint project. the actual querypoint extension is missing.
